### ISSUE TITLE
SetDB1

### ISSUE THREAD

**Issue by benzait27** [benzait27/Dauphine-Open-Data#11]
Implémenter une entité JPA et les méthodes permettant d’écrire et de lire depuis la BD les cours et triplets.

**Comment by oliviercailloux** [comment]
Note modifiée.
Config actuellement non portable, à cause Persistence.xml qui indique le fournisseur.
DAO inutile : les transactions ne doivent pas nécessairement être ouvertes et fermées à chaque opération, c’est l’appelant qui doit pouvoir le déterminer. Pas besoin d’une classe pour des méthodes qui ne contiennent qu’une ligne de code.
