### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by zedzed9** [benzait27/Dauphine-Open-Data#16]
Faire tourner le serveur en ligne grâce au service d’IBM

Ajout du manifest, création du compte IBM,  test de deploiement manuelle ok 

Prochaine etape raccordement avec travis (prochaine séance)

**Comment by zedzed9** [comment]
Une url permettant de vérifier le serveur : http://dauphine-open-data.eu-gb.mybluemix.net/appServlet

(servlet de test uniquement)
  
  Il est parfois nécessaire d'actualiser la page plusieurs fois ...

Actuellement deux lignes sur la page 

![image](https://user-images.githubusercontent.com/22102339/34642056-9b6122a6-f30d-11e7-9d4a-99b8bf6cc2c5.png)

**Comment by oliviercailloux** [comment]
Votre issue a une espace de trop à la fin de son nom (voir "Title" sur https://api.github.com/repos/benzait27/Dauphine-Open-Data/issues/16), raison pour laquelle mon système de suivi ne la voit pas. Veuillez la renommer pour enlever l’espace.

**Comment by zedzed9** [comment]
Monsieur,

Le changement vient d'être effectuer,

Merci

**Comment by oliviercailloux** [comment]
C’est un déploiement automatique qui est demandé (via Travis), non fait, de ce que je peux voir.
Le service tourne effectivement en ligne.
