### ISSUE TITLE
Projet, second

### ISSUE THREAD

**Issue by oliviercailloux** [benzait27/Dauphine-Open-Data#18]
Il faut protéger beaucoup mieux vos objets contre les pointeurs null et clarifier votre API. Exemple, Person (mais aussi Planning, …). FirstName peut être null, contrairement à ce qui est indiqué dans le commentaire ! (Exemple, à l’initialisation.) emails doit être une liste, éventuellement vide, et non null. Une information String manquante peut généralement être représentée par un string vide plutôt que par null. Etc. Voir BP Null.

Encore des erreurs détectées par Eclipse (tq Redundant specification of type).

VCal
Je déconseille une méthode pour une seule ligne de code (DateUtils).
Ne pas utiliser le fuseau horaire "local", qui dépend du serveur sur lequel votre code sera installé !
planning getLectures, pas getTeachings
Votre code serait plus clair, et plus flexible, avec une méthode transformant une "lecture" en "event" (plutôt que l’imbriquer dans un lambda). Si vous aimez les streams, vous pouvez ensuite transformer le stream de "lecture" en un stream de "event" (bien qu’on n’y gagne probablement pas en lisibilité, voir https://github.com/google/guava/wiki/FunctionalExplained#functions).
Si votre liste de teachings est supposée accessible en écriture (préciser dans la javadoc de planning), votre test peut être simplifié !
Indiquer dans la javadoc (actuellement incorrecte !) si le paramètre peut être null, ou quelles sont les contraintes.
Ne pas stocker la date d’une "lecture" avec une localdatetime, car c’est un événement situé précisément dans le temps !
Test utilise packages incorrects.

VCard mêmes remarques

ObjectsXML: BP Exceptions !

SetDB1: Bon début, mais code non fonctionnel (pas de persistence.xml). Votre code source doit être encodé en UTF8. Coder en anglais.

**Comment by benzait27** [comment]
most of these notes were taken into consideration
