### ISSUE TITLE
BasicClient

### ISSUE THREAD

**Issue by thomasgvd** [benzait27/Dauphine-Open-Data#31]
Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande, la visualisation des informations de base de Course et Person, et l’ajout de triplets associés. (1)

**Comment by benzait27** [comment]
could you please add how it work, and how we could see the person's and Cours's objects, please

**Comment by thomasgvd** [comment]
Basic Client retrieves the list of courses from the API url of the server with the path '/course'. 

It means if the app is executed in localhost, the API complete url will be 'http://www.localhost/Dauphine-Open-Data/course' and if executed on our server, it will be 'http://dauphine-open-data.eu-gb.mybluemix.net/course'. 

It then puts them into a javascript variable which is displayed in an html table. It's the same for the list of persons which use the API route '/person' to get the objects.

**Comment by benzait27** [comment]
thank you @thomasgvd
