### ISSUE TITLE
Projet général

### ISSUE THREAD

**Issue by oliviercailloux** [benzait27/Dauphine-Open-Data#8]
Bon travail.

BP Maven (noms packages uniques)
Configurer Eclipse (https://github.com/oliviercailloux/java-course/blob/master/Tools.adoc#configuration)
Optional ou garanties contre null.
Éviter les constructeurs avec très nombreux paramètres, car nuit à la lisibilité (expl Course).
Utiliser commentaires javadoc, pas //, où approprié
TeachingLang : utiliser plutôt Locale.
Dans Course : rôle du champ references pas clair (documenter). Indiquer parcours, etc., (exemple : cours de M2 ? MIAGE ?) en fonction de ce qui se trouve dans le schéma source. Un seul "auteur" par cours n’est pas suffisant : ce n’est pas nécessairement la même personne qui fait les TD, TP, et il peut même y avoir plusieurs classes de TD, TP, voire plusieurs classes de CM. Cela devrait être visible dans les données XML, idéalement.
Pas trouvé qui est WaffB ni kinodaime
FunctionType au singulier, car le nom désigne une instance, comme les autres classes
Teaching, “class that represents a class”, écrire plutôt “class that represents a lecture” (séance de cours). Renommer Teaching en Lecture, si c’est bien ça que vous souhaitez représenter. Il me semble en outre naturel et clair d’indiquer dans Lecture l’enseignant responsable du cours.
Pour pouvoir injecter dans une instance (injecter DateUtils d dans Teaching t), il faut que l’instance dans laquelle vous injectez (t) soit également gérée par le conteneur, donc qu’elle soit à son tour injectée (t injectée dans par exemple votre servlet).
BP Exceptions

**Comment by oliviercailloux** [comment]
Je ne sais toujours pas qui est WaffB.

**Comment by benzait27** [comment]
C est ouafa Boucenna

**Comment by benzait27** [comment]
most of these notes were taken into consideration
